name: Flutter Test

on:
  push:
    branches:
      - master
      - dev
  pull_request:
    branches:
      - master
      - dev

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.24.3"

      # Step 3: Install Dependencies
      - name: Install Dependencies
        run: flutter pub get

      # Step 4: Run Tests
      - name: Run Tests
        run: flutter test
